# Generated by Django 2.2 on 2019-04-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemons',
            name='img_name',
            field=models.PositiveIntegerField(),
        ),
    ]
