# Generated by Django 2.2 on 2019-04-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20190428_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='atk',
            field=models.PositiveIntegerField(verbose_name='ATK'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='cross_gen',
            field=models.PositiveIntegerField(verbose_name='Cross Gen'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='deff',
            field=models.PositiveIntegerField(verbose_name='DEF'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolution_stage',
            field=models.PositiveIntegerField(verbose_name='Evolution Stage'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='family_id',
            field=models.PositiveIntegerField(verbose_name='Family ID'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='future_evolve',
            field=models.PositiveIntegerField(verbose_name='Future Evolve'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_number',
            field=models.PositiveIntegerField(verbose_name='Pokedex Number'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='sta',
            field=models.PositiveIntegerField(verbose_name='STA'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='stat_total',
            field=models.PositiveIntegerField(verbose_name='STAT TOTAL'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type1',
            field=models.CharField(max_length=40, verbose_name='Type 1'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(max_length=40, verbose_name='Type 2'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weather1',
            field=models.CharField(max_length=40, verbose_name='Weather 1'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weather2',
            field=models.CharField(max_length=40, verbose_name='Weather 2'),
        ),
    ]
